services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todolist-network

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      GIN_MODE: debug
      DATABASE_URL: postgres://postgres:postgres@db:5432/todolist?sslmode=disable
      JWT_SECRET: secret
      PORT: 8080
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - todolist-network

  client:
    build: ./client
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "3000:80"
    networks:
      - todolist-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  db-data:

networks:
  todolist-network:
    driver: bridge